# Generated by Django 6.0.4 on 2026-04-14 12:25

import bot_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('slug', models.SlugField(default=bot_app.models.generate_slug, unique=True)),
                ('project_type', models.CharField(choices=[('neuro_chat', 'Neuro-Chat Bot'), ('webapp', 'Web App Boilerplate'), ('data_api', 'Data Analytics API'), ('custom', 'Custom Project')], default='custom', max_length=50, verbose_name='Тип проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('repo_url', models.URLField(verbose_name='URL репозитория')),
                ('branch', models.CharField(default='bot/docs-updates', max_length=100, verbose_name='Ветка')),
                ('git_token', models.CharField(blank=True, max_length=255, verbose_name='Git PAT')),
                ('use_ssh', models.BooleanField(default=False, verbose_name='Использовать SSH')),
                ('logs_path', models.CharField(default='bot/logs', max_length=200, verbose_name='Путь к логам')),
                ('docs_path', models.CharField(default='bot/docs', max_length=200, verbose_name='Путь к докам')),
                ('config_path', models.CharField(default='bot/config', max_length=200, verbose_name='Путь к конфигам')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents_meta', models.JSONField(blank=True, default=dict)),
                ('env_variables', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bot_app.project')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='Авто-синхронизация с ботом')),
                ('notify_commits', models.BooleanField(default=True, verbose_name='Уведомлять о коммитах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('last_commit_sha', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bot_app.project')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'unique_together': {('project', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('is_env', models.BooleanField(default=False, verbose_name='Это .env файл?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='bot_app.project')),
            ],
            options={
                'verbose_name': 'Конфиг',
                'verbose_name_plural': 'Конфиги',
                'unique_together': {('project', 'filename')},
            },
        ),
    ]
