apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: mvek-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer-service:local
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config